#!/usr/bin/env python3
"""Shared ``systemctl --user`` unit management for the ambient CLI/tray.

Both ``ambientctl`` and ``ambienttray`` install/enable/disable/uninstall a
per-user systemd unit under ``~/.config/systemd/user/``.  This module is the one
implementation of that (unit path, write + daemon-reload, remove + disable), so
the two entry points cannot drift.

Caveats:
  - ``systemctl`` is per-user only; never invoke without ``--user``.
  - ``systemctl()`` exits the process when ``systemctl`` itself is missing, and
    only raises on failure when ``check=True`` (ambientctl historically tolerated
    failures, ambienttray did not — callers pass the flag accordingly).
  - Units are plain text generated by the entry points; this module does not
    know their contents.

Used by: ambientctl, ambienttray.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path


def systemctl(args: list[str], check: bool = False) -> None:
    """Run ``systemctl --user <args>``."""
    shutil.which("systemctl") or sys.exit("error: systemctl not found")
    subprocess.run(["systemctl", "--user", *args], check=check)


def unit_path(name: str) -> Path:
    """Absolute path of the user unit file ``name`` (e.g. "ambient.service")."""
    return Path.home() / ".config" / "systemd" / "user" / name


def install_unit(name: str, text: str) -> Path:
    """Write ``text`` to the user unit ``name`` and ``daemon-reload``.

    Returns the unit path; the caller prints the "next: enable" hint.
    """
    path = unit_path(name)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    systemctl(["daemon-reload"])
    return path


def uninstall_unit(name: str) -> bool:
    """Disable ``name``, remove the unit file and ``daemon-reload``.

    Returns True if a unit file was present and removed, False otherwise.
    """
    systemctl(["disable", name])
    path = unit_path(name)
    if path.exists():
        path.unlink()
        systemctl(["daemon-reload"])
        return True
    return False


def render_user_unit(
    *,
    generated_by: str,
    description: str,
    exec_start: str,
    syslog_identifier: str,
    after: str = "graphical-session.target",
    environment: str | None = None,
    restart_comment: str | None = None,
    syslog_comment: str | None = None,
) -> str:
    """Render a per-user service unit (shared by ``ambientctl`` + ``ambienttray``).

    All units share the same skeleton (``Type=simple``, ``Restart=on-failure``,
    idle I/O priority, journald identifier); callers supply the description,
    ExecStart, identifier and any explanatory comments.  Multi-line comment
    strings are emitted one ``#`` line each.
    """
    lines = [
        f"# Generated by `{generated_by} install` — manage with {generated_by} / systemctl --user",
        "[Unit]",
        f"Description={description}",
        f"After={after}",
        "PartOf=graphical-session.target",
        "",
        "[Service]",
        "Type=simple",
        f"ExecStart={exec_start}",
    ]
    if environment:
        lines.append(f"Environment={environment}")
    if restart_comment:
        lines.extend(f"# {ln}" for ln in restart_comment.splitlines())
    lines += ["Restart=on-failure", "RestartSec=3", "Nice=15", "IOSchedulingClass=idle"]
    if syslog_comment:
        lines.extend(f"# {ln}" for ln in syslog_comment.splitlines())
    lines += [
        f"SyslogIdentifier={syslog_identifier}",
        "",
        "[Install]",
        "WantedBy=default.target",
        "",
    ]
    return "\n".join(lines)


def install_cli(name: str, text: str, enable_hint: str) -> int:
    """Install ``text`` as unit ``name`` and print the standard confirmation."""
    unit = install_unit(name, text)
    print(f"installed user unit: {unit}")
    print(f"next:  {enable_hint}")
    return 0


def uninstall_cli(name: str) -> int:
    """Remove unit ``name`` and print the standard confirmation."""
    unit = unit_path(name)
    if uninstall_unit(name):
        print(f"removed {unit}")
    else:
        print("no unit file present")
    return 0
