#!/usr/bin/env python3
"""Shared ``systemctl --user`` unit management for the ambient CLI/tray.

Both ``ambientctl`` and ``ambienttray`` install/enable/disable/uninstall a
per-user systemd unit under ``~/.config/systemd/user/``.  This module is the one
implementation of that (unit path, write + daemon-reload, remove + disable), so
the two entry points cannot drift.

Caveats:
  - ``systemctl`` is per-user only; never invoke without ``--user``.
  - ``systemctl()`` exits the process when ``systemctl`` itself is missing, and
    only raises on failure when ``check=True`` (ambientctl historically tolerated
    failures, ambienttray did not — callers pass the flag accordingly).
  - Units are plain text generated by the entry points; this module does not
    know their contents.

Used by: ambientctl, ambienttray.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path


def systemctl(args: list[str], check: bool = False) -> None:
    """Run ``systemctl --user <args>``."""
    shutil.which("systemctl") or sys.exit("error: systemctl not found")
    subprocess.run(["systemctl", "--user", *args], check=check)


def unit_path(name: str) -> Path:
    """Absolute path of the user unit file ``name`` (e.g. "ambient.service")."""
    return Path.home() / ".config" / "systemd" / "user" / name


def install_unit(name: str, text: str) -> Path:
    """Write ``text`` to the user unit ``name`` and ``daemon-reload``.

    Returns the unit path; the caller prints the "next: enable" hint.
    """
    path = unit_path(name)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    systemctl(["daemon-reload"])
    return path


def uninstall_unit(name: str) -> bool:
    """Disable ``name``, remove the unit file and ``daemon-reload``.

    Returns True if a unit file was present and removed, False otherwise.
    """
    systemctl(["disable", name])
    path = unit_path(name)
    if path.exists():
        path.unlink()
        systemctl(["daemon-reload"])
        return True
    return False
